Popular movie tile
JaroslawOgonowski/movie-browser pull request #13
Opened 2023-04-26 14:09 UTC by saimoNN37

Filmy pojawiają się ale jeszcze niestety bez gatunków

2023-04-26 15:26 UTC, JaroslawOgonowski requested changes

2023-04-26 15:26 UTC, JaroslawOgonowski commented on src/features/genresSaga.js
> +}
Te pliki z generes dałbym w nowy folder Generes i wrzucił do moviesPage

2023-04-26 15:26 UTC, JaroslawOgonowski commented on src/features/genresSlice.js
> +export default genresSlice.reducer;
tak samo ten plik

2023-04-26 15:26 UTC, JaroslawOgonowski commented on src/features/getGenres.js
> +}
no i ten

2023-04-26 15:26 UTC, JaroslawOgonowski commented on src/core/rootSaga.js
>  };
zwyczajowo jako funkcja get nazywamy fetcha - tu wystarczy generesSaga

2023-04-26 15:26 UTC, JaroslawOgonowski commented on src/features/genresSaga.js
> +export function* getGenresSaga() {
i tak samo tu- generesSaga zamiast getGenersSaga

2023-04-26 15:26 UTC, JaroslawOgonowski commented on src/features/genresSaga.js
> +  yield takeLatest(fetchGenres.type, fetchGenresHandler);
tu ten type jest zbędny

2023-04-26 15:26 UTC, JaroslawOgonowski commented on src/features/genresSlice.js
> +            status: "loading",
tu jednak dałbym 
`generes:null`
na wypadek przeładowywania, niech w tym czasie tablica się wyczyści

2023-04-26 15:26 UTC, JaroslawOgonowski commented on src/features/genresSlice.js
> +            status: "error",
i tak samo tu `generes:null` żeby nam się ładnie stan wyczyścił w razie błędu

2023-04-26 15:26 UTC, JaroslawOgonowski commented on src/features/genresSlice.js
> +export const selectGenres = (state) => state.genres.genres;
tu się krzaczy- powinno być` export const selectGenres = (state) => state.genres`

2023-04-26 15:26 UTC, JaroslawOgonowski commented on src/features/genresSlice.js
> +export const selectGenresStatus = (state) => selectGenres(state).status;
tu wykorzystujesz tą linijkę wyżej a skoro ona jest źle to tutaj też nie możesz dobić się do statusu

2023-04-27 07:41 UTC, saimoNN37 commented on src/features/genresSlice.js
> +export default genresSlice.reducer;
Poprawione, możesz teraz sprawdzić

2023-04-27 12:25 UTC, JaroslawOgonowski approved these changes

2023-04-27 12:25 UTC, JaroslawOgonowski commented on src/features/getGenres.js
> +      https://api.themoviedb.org/3/genre/movie/list?api_key=b2d37cc721e707dfb0e0916acc249569&language=en-US`);
i tutaj klucz można wyciągnąć z pliku API no i  `https://api.themoviedb.org/3/genre` wrzucić też tam jako generesAPI

2023-04-27 12:25 UTC, JaroslawOgonowski commented on src/features/moviesPage/index.js
>      console.log(a.results)
do usunięcia

2023-04-27 12:25 UTC, JaroslawOgonowski commented on src/features/moviesPage/index.js
>            {a.results.map(movie => (
to "a" było przykładowe :) trzeba to zmienić na popularMovies

2023-04-27 12:29 UTC, merged